# Generated by Django 5.0.1 on 2024-01-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_assignment_progress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='progress_status',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('ongoing', 'Ongoing'), ('incapable', 'Incapable'), ('completed', 'Completed')], default='unseen', max_length=10),
        ),
    ]
