# Generated by Django 5.0.1 on 2024-01-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='progress_status',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('ongoing', 'Ongoing'), ('incapable', 'Ongoing'), ('completed', 'Completed')], default='unseen', max_length=10),
        ),
    ]
