# Generated by Django 5.0.1 on 2024-01-19 09:18

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default=tickets.models.generate_ticket_number, editable=False, max_length=255, unique=True),
        ),
    ]
