# Generated by Django 5.0.1 on 2024-01-19 09:24

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(upload_to=tickets.models.upload_path),
        ),
    ]
